import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import type { Readable, Writable } from 'node:stream';

import { createAppContext } from '../app-context.js';
import { ensureApplicationDirectories, loadConfig } from '../config/load.js';
import type { AppConfig } from '../config/schema.js';

export interface InstallWizardOptions {
  configPath: string;
  cwd?: string;
  yes?: boolean;
  production?: boolean;
  skipLogin?: boolean;
  pairingPhone?: string;
  input?: Readable;
  output?: Writable;
  authenticate?: (config: AppConfig, pairingPhone?: string) => Promise<void>;
}

export interface InstallWizardResult {
  config: AppConfig;
  configPath: string;
  createdConfig: boolean;
  authenticated: boolean;
}

function envLine(name: string, value: string | number | boolean): string {
  return `${name}=${String(value).replaceAll('\n', '')}`;
}

function defaultTimezone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
  } catch {
    return 'UTC';
  }
}

function write(output: Writable, message: string): void {
  output.write(`${message}\n`);
}

function yesValue(value: string, defaultAnswer: boolean): boolean {
  const normalized = value.trim().toLowerCase();
  if (!normalized) return defaultAnswer;
  return ['y', 'yes', '1', 'true', 'ب', 'بله', 'آره'].includes(normalized);
}

export async function runInstallWizard(options: InstallWizardOptions): Promise<InstallWizardResult> {
  const cwd = options.cwd ?? process.cwd();
  const input = options.input ?? process.stdin;
  const output = options.output ?? process.stdout;
  const configPath = resolve(cwd, options.configPath);
  const interactive = !options.yes;
  if (interactive && (!(input as NodeJS.ReadStream).isTTY || !(output as NodeJS.WriteStream).isTTY)) {
    throw new Error('Interactive installation requires a TTY; use --yes --skip-login for safe non-interactive setup.');
  }

  const prompt = interactive ? createInterface({ input, output }) : undefined;
  const ask = async (question: string, fallback = ''): Promise<string> => {
    if (!prompt) return fallback;
    const suffix = fallback ? ` [${fallback}]` : '';
    const answer = await prompt.question(`${question}${suffix}: `);
    return answer.trim() || fallback;
  };
  const confirm = async (question: string, fallback: boolean): Promise<boolean> => {
    if (!prompt) return fallback;
    const marker = fallback ? 'Y/n' : 'y/N';
    return yesValue(await prompt.question(`${question} [${marker}]: `), fallback);
  };

  try {
    write(output, '');
    write(output, 'WTS — SajadBot WhatsApp guided setup');
    write(output, '--------------------------------------------');
    const nodeMajor = Number(process.versions.node.split('.')[0]);
    write(output, `[1/5] Checking Node.js: ${process.version}`);
    if (nodeMajor < 20) throw new Error('Node.js 20 or newer is required.');
    write(output, '      ✓ Node.js version is supported.');

    let createdConfig = false;
    write(output, `[2/5] Configuration: ${configPath}`);
    if (existsSync(configPath)) {
      const reuse = await confirm('A configuration file already exists. Reuse it without changes?', true);
      if (!reuse) {
        throw new Error('Setup stopped to avoid overwriting the file; choose another path with --config.');
      }
      write(output, '      ✓ Existing configuration preserved.');
    } else {
      const configDir = dirname(configPath);
      const stateDir = await ask('Data storage path', join(configDir, 'data'));
      const timezone = await ask('IANA time zone', defaultTimezone());
      const dryRun = options.production ? false : await confirm('Enable safe dry-run mode for now?', true);
      const pairingPhone = options.pairingPhone ?? (interactive ? await ask('Pairing phone with country code (optional)', '') : '');
      const lines = [
        '# Generated by wts install',
        envLine('DATABASE_PATH', join(stateDir, 'app.db')),
        envLine('STATE_DIR', stateDir),
        envLine('MEDIA_DIR', join(stateDir, 'media')),
        envLine('LOCK_PATH', join(stateDir, 'daemon.lock')),
        envLine('LOG_LEVEL', 'info'),
        envLine('TIMEZONE', timezone),
        '',
        envLine('DRY_RUN', dryRun),
        envLine('WORKER_POLL_MS', 1000),
        envLine('SEND_INTERVAL_MS', 8000),
        envLine('MAX_ATTEMPTS', 5),
        envLine('RETRY_BASE_MS', 5000),
        envLine('RETRY_MAX_MS', 300000),
        envLine('MAX_MEDIA_BYTES', 2147483648),
        '',
        envLine('SELF_CONTROLLER_ENABLED', false),
        envLine('PAIRING_PHONE', pairingPhone),
        '',
      ];
      mkdirSync(configDir, { recursive: true, mode: 0o700 });
      writeFileSync(configPath, lines.join('\n'), { encoding: 'utf8', flag: 'wx', mode: 0o600 });
      createdConfig = true;
      write(output, '      ✓ Configuration file created.');
    }

    write(output, '[3/5] Validating configuration and creating secure paths');
    const config = loadConfig({ envFile: configPath, cwd });
    ensureApplicationDirectories(config);
    write(output, `      ✓ state=${config.stateDir}`);
    write(output, `      ✓ media=${config.mediaDir}`);

    write(output, '[4/5] Preparing SQLite and running migrations');
    const context = createAppContext(config);
    const journalMode = context.database.getJournalMode();
    context.audit.add('interactive_install', { actor: 'cli', details: { createdConfig } });
    context.close();
    write(output, `      ✓ Database is ready; journal=${journalMode}.`);

    let authenticated = false;
    const canAuthenticate = !config.dryRun && !options.skipLogin && Boolean(options.authenticate);
    const loginNow = canAuthenticate && !options.yes ? await confirm('Link WhatsApp now?', true) : false;
    if (loginNow && options.authenticate) {
      write(output, '[5/5] WhatsApp authentication; scan the QR from Linked devices.');
      const pairingPhone = options.pairingPhone ?? config.pairingPhone;
      await options.authenticate(config, pairingPhone);
      authenticated = true;
      write(output, '      ✓ WhatsApp authentication succeeded.');
    } else {
      write(output, '[5/5] WhatsApp authentication skipped for now.');
      if (config.dryRun) write(output, '      • The project is in dry-run mode; real delivery remains disabled.');
      else write(output, `      • Next step: wts --config "${configPath}" auth login`);
    }

    write(output, '');
    write(output, 'Initial setup is complete. Run this health check:');
    write(output, `  wts --config "${configPath}" check`);
    if (!config.dryRun) {
      write(output, 'For real delivery, discover groups and explicitly allow the intended destination:');
      write(output, `  wts --config "${configPath}" groups refresh`);
      write(output, `  wts --config "${configPath}" groups list`);
      write(output, `  wts --config "${configPath}" groups allow <JID-or-alias>`);
    }
    return { config, configPath, createdConfig, authenticated };
  } finally {
    prompt?.close();
  }
}
